# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialprice', '0002_auto_20161102_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaseorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=32, verbose_name='厂商')),
                ('part', models.CharField(max_length=128, verbose_name='品名')),
                ('spec', models.CharField(max_length=128, verbose_name='规格')),
                ('qty', models.IntegerField(default=0, verbose_name='数量')),
                ('unit', models.CharField(max_length=32, verbose_name='单位')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='单价')),
                ('podate', models.DateTimeField(max_length=10, verbose_name='订单日期')),
            ],
            options={
                'verbose_name': '採購',
                'verbose_name_plural': '採購',
            },
        ),
    ]
