# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materialprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=32, verbose_name='牌号')),
                ('pricedate', models.CharField(max_length=10, verbose_name='行情日期')),
                ('num', models.IntegerField(default=0, verbose_name='項次')),
                ('avg', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='平均价')),
            ],
            options={
                'verbose_name': '回報',
                'verbose_name_plural': '回報',
            },
        ),
    ]
