# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialprice', '0004_auto_20161103_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FB', models.CharField(max_length=32, verbose_name='供应商')),
                ('FC', models.CharField(max_length=32, verbose_name='业务伙伴')),
                ('FD', models.CharField(max_length=64, verbose_name='物料代码')),
                ('FE', models.CharField(max_length=64, verbose_name='品名')),
                ('FF', models.DateField(verbose_name='进料日期')),
                ('FG', models.CharField(max_length=64, verbose_name='收料单号')),
                ('FH', models.CharField(default='KG', max_length=32, verbose_name='单位')),
                ('FI', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='收货数量')),
                ('FJ', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='含税单价')),
                ('FK', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='未税单价')),
                ('FL', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='未税金额')),
                ('FM', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='含税金额')),
                ('FN', models.CharField(default='原料类', max_length=32, verbose_name='类别')),
                ('FO', models.CharField(default='2016-09', max_length=32, verbose_name='年月份')),
            ],
            options={
                'verbose_name': '進料表',
                'verbose_name_plural': '進料表',
            },
        ),
    ]
