# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowchartprocess',
            old_name='process_name',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='flowchartprocess',
            old_name='process_desc',
            new_name='d',
        ),
        migrations.RemoveField(
            model_name='flowchart',
            name='mold_num',
        ),
        migrations.AddField(
            model_name='flowchart',
            name='by1',
            field=models.CharField(default='.', max_length=32, verbose_name='編制'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='by1date',
            field=models.DateField(null=True, verbose_name='編制日期'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='by2',
            field=models.CharField(max_length=32, null=True, verbose_name='審核'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='by2date',
            field=models.DateField(null=True, verbose_name='審核日期'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='by3',
            field=models.CharField(max_length=32, null=True, verbose_name='批准'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='by3date',
            field=models.DateField(null=True, verbose_name='批准日期'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='c1',
            field=models.CharField(default='.', max_length=32, verbose_name='模號'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='c2',
            field=models.CharField(default='.', max_length=32, verbose_name='模穴'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='e1',
            field=models.CharField(default='.', max_length=32, verbose_name='圖面版本'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='e2',
            field=models.CharField(default='.', max_length=32, verbose_name='表面等級'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='g1',
            field=models.CharField(default='.', max_length=32, verbose_name='版序'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='g2',
            field=models.CharField(default='.', max_length=32, verbose_name='材質'),
        ),
        migrations.AddField(
            model_name='flowchartprocess',
            name='a',
            field=models.IntegerField(default=0, verbose_name='序號'),
        ),
        migrations.AddField(
            model_name='flowchartprocess',
            name='b',
            field=models.CharField(default='.', max_length=32, verbose_name='部門'),
        ),
        migrations.AddField(
            model_name='flowchartprocess',
            name='e',
            field=models.CharField(default='.', max_length=256, verbose_name='品質要求'),
        ),
        migrations.AddField(
            model_name='flowchartprocess',
            name='f',
            field=models.CharField(default='.', max_length=32, verbose_name='設備'),
        ),
        migrations.AddField(
            model_name='flowchartprocess',
            name='g',
            field=models.CharField(default='.', max_length=32, verbose_name='刀、治、模具'),
        ),
        migrations.AddField(
            model_name='flowchartprocess',
            name='h',
            field=models.CharField(default='.', max_length=32, verbose_name='檢具'),
        ),
    ]
