# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0002_auto_20161125_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowchart',
            name='by1date',
        ),
        migrations.RemoveField(
            model_name='flowchart',
            name='by2',
        ),
        migrations.RemoveField(
            model_name='flowchart',
            name='by2date',
        ),
        migrations.RemoveField(
            model_name='flowchart',
            name='by3',
        ),
        migrations.RemoveField(
            model_name='flowchart',
            name='by3date',
        ),
    ]
