# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0004_flowchart_by1date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowchart',
            name='by2',
            field=models.CharField(max_length=32, null=True, verbose_name='審核'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='by2date',
            field=models.DateField(blank=True, null=True, verbose_name='審核日期'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='by3',
            field=models.CharField(max_length=32, null=True, verbose_name='批准'),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='by3date',
            field=models.DateField(blank=True, null=True, verbose_name='批准日期'),
        ),
    ]
