# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyreport', '0003_auto_20161028_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocation',
            name='vocationnum',
            field=models.IntegerField(default=1, verbose_name='第幾次'),
        ),
    ]
