# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyreport', '0004_auto_20161028_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vocation',
            new_name='Vacation',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='vocationfrom',
            new_name='vacationfrom',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='vocationnum',
            new_name='vacationnum',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='vocationto',
            new_name='vacationto',
        ),
    ]
