# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyreport', '0006_vacation_vacationstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32, verbose_name='員工姓名')),
                ('mailbox1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='fulltech-metal.net')),
                ('mailbox2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='skyrock-casting.org')),
                ('mailbox3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='fulltech-metal.com')),
                ('remarks', models.CharField(max_length=200, verbose_name='備註')),
            ],
            options={
                'verbose_name': '郵箱',
                'verbose_name_plural': '郵箱',
            },
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vacationstatus',
            field=models.CharField(choices=[('報到日期', '報到日期'), ('已休假', '已休假'), ('申請休假', '申請休假')], default='申請休假', max_length=50, verbose_name='狀態'),
        ),
    ]
