# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyreport', '0007_auto_20161028_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='mailbox4',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='skyrock-casting.com'),
        ),
    ]
